<?php
/**
 * Plugin Name: Basketmania Camp System
 * Description: Niezależny system zapisów, CRM, umów potwierdzanych kodem SMS, płatności Stripe i dokumentów dla Basketmania Camp.
 * Version: 1.12.18
 * Release build: v1.12.18
 * Author: Basketmania Camp
 * Text Domain: basketmania-camp
 * Requires at least: 6.5
 * Requires PHP: 8.1
 */

if (!defined('ABSPATH')) exit;

define('BCS_VERSION', '1.12.18');
define('BCS_FILE', __FILE__);
define('BCS_DIR', plugin_dir_path(__FILE__));
define('BCS_URL', plugin_dir_url(__FILE__));

require_once BCS_DIR . 'includes/class-bcs-updater.php';
BCS_Updater::init();

require_once BCS_DIR . 'includes/class-bcs-db.php';
require_once BCS_DIR . 'includes/class-bcs-utils.php';
require_once BCS_DIR . 'includes/class-bcs-locks.php';
require_once BCS_DIR . 'includes/class-bcs-sms.php';
require_once BCS_DIR . 'includes/class-bcs-mailer.php';
require_once BCS_DIR . 'includes/class-bcs-mailbox.php';
require_once BCS_DIR . 'includes/class-bcs-agreements.php';
require_once BCS_DIR . 'includes/class-bcs-payments.php';
require_once BCS_DIR . 'includes/class-bcs-admin.php';
require_once BCS_DIR . 'includes/class-bcs-feedback.php';
require_once BCS_DIR . 'includes/class-bcs-frontend.php';
require_once BCS_DIR . 'includes/class-bcs-documents.php';
require_once BCS_DIR . 'includes/class-bcs-invoices.php';
require_once BCS_DIR . 'includes/class-bcs-invoice-batches.php';
require_once BCS_DIR . 'includes/class-bcs-communications.php';
require_once BCS_DIR . 'includes/class-bcs-notification-settings.php';
require_once BCS_DIR . 'includes/class-bcs-workflow-modernization.php';
require_once BCS_DIR . 'includes/class-bcs-release-0187.php';
require_once BCS_DIR . 'includes/class-bcs-release-0189.php';
require_once BCS_DIR . 'includes/class-bcs-release-0190.php';
require_once BCS_DIR . 'includes/class-bcs-release-0190-hardening.php';
require_once BCS_DIR . 'includes/class-bcs-release-0191.php';
require_once BCS_DIR . 'includes/class-bcs-release-0192.php';
require_once BCS_DIR . 'includes/class-bcs-release-0193.php';
require_once BCS_DIR . 'includes/class-bcs-release-0194.php';
require_once BCS_DIR . 'includes/class-bcs-release-0200.php';
require_once BCS_DIR . 'includes/class-bcs-release-02024.php';
require_once BCS_DIR . 'includes/class-bcs-release-0254.php';
require_once BCS_DIR . 'includes/class-bcs-release-027.php';
require_once BCS_DIR . 'includes/class-bcs-release-028.php';
require_once BCS_DIR . 'includes/class-bcs-release-029.php';
require_once BCS_DIR . 'includes/class-bcs-release-029-gate.php';
require_once BCS_DIR . 'includes/class-bcs-release-030.php';
require_once BCS_DIR . 'includes/class-bcs-release-031.php';
require_once BCS_DIR . 'includes/class-bcs-release-032.php';
require_once BCS_DIR . 'includes/class-bcs-release-032-list-hotfix.php';
require_once BCS_DIR . 'includes/class-bcs-release-036.php';
require_once BCS_DIR . 'includes/class-bcs-release-037.php';
require_once BCS_DIR . 'includes/class-bcs-release-038.php';
require_once BCS_DIR . 'includes/class-bcs-release-039.php';
require_once BCS_DIR . 'includes/class-bcs-release-040.php';
require_once BCS_DIR . 'includes/class-bcs-release-041.php';
require_once BCS_DIR . 'includes/class-bcs-release-042.php';
require_once BCS_DIR . 'includes/class-bcs-release-043.php';
require_once BCS_DIR . 'includes/class-bcs-release-044.php';
require_once BCS_DIR . 'includes/class-bcs-release-045.php';
require_once BCS_DIR . 'includes/class-bcs-release-046.php';
require_once BCS_DIR . 'includes/class-bcs-release-047.php';
require_once BCS_DIR . 'includes/class-bcs-release-048.php';
require_once BCS_DIR . 'includes/class-bcs-release-051.php';
require_once BCS_DIR . 'includes/class-bcs-release-051-storage.php';
require_once BCS_DIR . 'includes/class-bcs-release-052.php';
require_once BCS_DIR . 'includes/class-bcs-release-053.php';
require_once BCS_DIR . 'includes/class-bcs-release-054.php';
require_once BCS_DIR . 'includes/class-bcs-release-055.php';
require_once BCS_DIR . 'includes/class-bcs-release-056.php';
require_once BCS_DIR . 'includes/class-bcs-release-057.php';
require_once BCS_DIR . 'includes/class-bcs-release-058.php';
require_once BCS_DIR . 'includes/class-bcs-release-059.php';
require_once BCS_DIR . 'includes/class-bcs-release-060.php';
require_once BCS_DIR . 'includes/class-bcs-release-061.php';
require_once BCS_DIR . 'includes/class-bcs-release-062.php';
require_once BCS_DIR . 'includes/class-bcs-release-063.php';
require_once BCS_DIR . 'includes/class-bcs-release-064.php';
require_once BCS_DIR . 'includes/class-bcs-release-065.php';
require_once BCS_DIR . 'includes/class-bcs-release-065-log-context.php';
require_once BCS_DIR . 'includes/class-bcs-release-066.php';
require_once BCS_DIR . 'includes/class-bcs-release-067.php';
require_once BCS_DIR . 'includes/class-bcs-release-068.php';
require_once BCS_DIR . 'includes/class-bcs-release-069.php';
require_once BCS_DIR . 'includes/class-bcs-agreement-pdf-v2.php';
require_once BCS_DIR . 'includes/class-bcs-release-071.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-config.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-secret.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-install.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-crypto.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-client.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-auth.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-fa3.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-service.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-invoice-flow.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-test-document-service.php';
require_once BCS_DIR . 'includes/class-bcs-ksef-admin.php';
require_once BCS_DIR . 'includes/class-bcs-release-072.php';
require_once BCS_DIR . 'includes/class-bcs-release-073.php';
require_once BCS_DIR . 'includes/class-bcs-release-074.php';
require_once BCS_DIR . 'includes/class-bcs-release-075-organizer.php';
require_once BCS_DIR . 'includes/class-bcs-release-075.php';
require_once BCS_DIR . 'includes/class-bcs-release-076.php';
require_once BCS_DIR . 'includes/class-bcs-release-076-compat.php';
require_once BCS_DIR . 'includes/class-bcs-release-077.php';
require_once BCS_DIR . 'includes/class-bcs-release-078.php';
require_once BCS_DIR . 'includes/class-bcs-release-079.php';
require_once BCS_DIR . 'includes/class-bcs-release-080.php';
require_once BCS_DIR . 'includes/class-bcs-release-081.php';
require_once BCS_DIR . 'includes/class-bcs-release-082.php';
require_once BCS_DIR . 'includes/class-bcs-release-083.php';
require_once BCS_DIR . 'includes/class-bcs-release-084.php';
require_once BCS_DIR . 'includes/class-bcs-release-085.php';
require_once BCS_DIR . 'includes/class-bcs-release-086.php';
require_once BCS_DIR . 'includes/class-bcs-release-087.php';
require_once BCS_DIR . 'includes/class-bcs-release-088.php';
require_once BCS_DIR . 'includes/class-bcs-release-089.php';
require_once BCS_DIR . 'includes/class-bcs-release-090.php';
require_once BCS_DIR . 'includes/class-bcs-release-091.php';
require_once BCS_DIR . 'includes/class-bcs-release-092.php';
require_once BCS_DIR . 'includes/class-bcs-release-093.php';
require_once BCS_DIR . 'includes/class-bcs-release-094.php';
require_once BCS_DIR . 'includes/class-bcs-release-095.php';
require_once BCS_DIR . 'includes/class-bcs-release-096.php';
require_once BCS_DIR . 'includes/class-bcs-release-097.php';
require_once BCS_DIR . 'includes/class-bcs-release-098.php';
require_once BCS_DIR . 'includes/class-bcs-release-099.php';
require_once BCS_DIR . 'includes/class-bcs-release-100.php';
require_once BCS_DIR . 'includes/class-bcs-release-101.php';
require_once BCS_DIR . 'includes/class-bcs-release-103.php';
require_once BCS_DIR . 'includes/class-bcs-release-104.php';
require_once BCS_DIR . 'includes/class-bcs-release-105.php';
require_once BCS_DIR . 'includes/class-bcs-release-106.php';
require_once BCS_DIR . 'includes/class-bcs-release-107.php';
require_once BCS_DIR . 'includes/class-bcs-release-108.php';
require_once BCS_DIR . 'includes/class-bcs-release-109.php';
require_once BCS_DIR . 'includes/class-bcs-release-110.php';
require_once BCS_DIR . 'includes/class-bcs-release-111.php';
require_once BCS_DIR . 'includes/class-bcs-release-11216.php';
require_once BCS_DIR . 'includes/class-bcs-templates.php';
require_once BCS_DIR . 'includes/class-bcs-pdf.php';
require_once BCS_DIR . 'includes/class-bcs-camp-reports.php';
require_once BCS_DIR . 'includes/class-bcs-service-center.php';
require_once BCS_DIR . 'includes/class-bcs-deposits.php';
require_once BCS_DIR . 'includes/class-bcs-workflow.php';
require_once BCS_DIR . 'includes/class-bcs-workflow-engine.php';
require_once BCS_DIR . 'includes/class-bcs-template-engine.php';
require_once BCS_DIR . 'includes/class-bcs-document-engine.php';
require_once BCS_DIR . 'includes/class-bcs-communication-engine.php';
require_once BCS_DIR . 'includes/class-bcs-core.php';
require_once BCS_DIR . 'includes/class-bcs-crm.php';
require_once BCS_DIR . 'includes/class-bcs-qualification.php';

register_activation_hook(__FILE__, ['BCS_DB', 'activate']);

add_action('plugins_loaded', function () {
    BCS_DB::maybe_upgrade();
    BCS_DB::init();
    BCS_Locks::init();
    BCS_Mailer::init();
    BCS_Mailbox::init();
    BCS_Agreements::init();
    BCS_Payments::init();
    BCS_Admin::init();
    BCS_Feedback::init();
    BCS_Frontend::init();
    BCS_Documents::init();
    BCS_Invoices::init();
    BCS_Invoice_Batches::init();
    BCS_Communications::init();
    BCS_Notification_Settings::init();
    BCS_Workflow_Modernization::init();
    BCS_Release_0187::init();
    BCS_Release_0189::init();
    BCS_Release_0190::init();
    BCS_Release_0190_Hardening::init();
    BCS_Release_0191::init();
    BCS_Release_0192::init();
    BCS_Release_0193::init();
    BCS_Release_0194::init();
    BCS_Release_0200::init();
    BCS_Release_02024::init();
    BCS_Release_0254::init();
    BCS_Release_027::init();
    BCS_Release_028::init();
    BCS_Release_029::init();
    BCS_Release_029_Gate::init();
    BCS_Release_030::init();
    BCS_Release_031::init();
    BCS_Release_032::init();
    BCS_Release_032_List_Hotfix::init();
    BCS_Release_036::init();
    BCS_Release_037::init();
    BCS_Release_040::init();
    BCS_Release_041::init();
    BCS_Release_042::init();
    BCS_Release_043::init();
    BCS_Release_044::init();
    BCS_Release_045::init();
    BCS_Release_046::init();
    BCS_Release_047::init();
    BCS_Release_048::init();
    BCS_Release_051::init();
    BCS_Release_051_Storage::init();
    BCS_Release_052::init();
    BCS_Release_053::init();
    BCS_Release_054::init();
    BCS_Release_055::init();
    BCS_Release_056::init();
    BCS_Release_057::init();
    BCS_Release_058::init();
    BCS_Release_059::init();
    BCS_Release_060::init();
    BCS_Release_061::init();
    BCS_Release_062::init();
    BCS_Release_063::init();
    BCS_Release_064::init();
    BCS_Release_065::init();
    BCS_Release_065_Log_Context::init();
    BCS_Release_066::init();
    BCS_Release_067::init();
    BCS_Release_068::init();
    BCS_Release_069::init();
    BCS_Agreement_PDF_V2::init();
    BCS_Release_071::init();
    BCS_Release_072::init();
    BCS_Release_073::init();
    BCS_Release_074::init();
    BCS_Release_075_Organizer::init();
    BCS_Release_075::init();
    BCS_KSeF_Invoice_Flow::init();
    BCS_Release_076::init();
    BCS_Release_076_Compat::init();
    BCS_Release_077::init();
    BCS_Release_078::init();
    BCS_Release_079::init();
    BCS_Release_080::init();
    BCS_Release_081::init();
    BCS_Release_082::init();
    BCS_Release_083::init();
    BCS_Release_084::init();
    BCS_Release_085::init();
    BCS_Release_086::init();
    BCS_Release_087::init();
    BCS_Release_088::init();
    BCS_Release_089::init();
    BCS_Release_090::init();
    BCS_Release_091::init();
    BCS_Templates::init();
    BCS_PDF::init();
    BCS_Camp_Reports::init();
    BCS_Release_092::init();
    BCS_Release_093::init();
    BCS_Release_094::init();
    BCS_Release_095::init();
    BCS_Release_096::init();
    BCS_Release_097::init();
    BCS_Release_098::init();
    BCS_Release_099::init();
    BCS_Release_100::init();
    BCS_Release_101::init();
    BCS_Release_103::init();
    BCS_Release_104::init();
    BCS_Release_105::init();
    BCS_Release_106::init();
    BCS_Release_107::init();
    BCS_Release_108::init();
    BCS_Release_109::init();
    BCS_Release_110::init();
    BCS_Release_111::init();
    BCS_Release_11216::init();
    BCS_Service_Center::init();
    BCS_Workflow::init();
    BCS_Deposits::init();
    BCS_Core::init();
    BCS_CRM::init();
    BCS_Qualification::init();
});
