<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$bootstrap = (string)file_get_contents($root.'/basketmania-camp-system.php');
$source = (string)file_get_contents($root.'/includes/class-bcs-release-078.php');

$fail = static function(string $message): void {
    fwrite(STDERR, "FAIL: {$message}\n");
    exit(1);
};

preg_match('/\* Version:\s*([0-9.]+)/', $bootstrap, $headerVersion);
preg_match("/define\('BCS_VERSION',\s*'([^']+)'\)/", $bootstrap, $constantVersion);
$currentVersion = $headerVersion[1] ?? '';
if ($currentVersion !== '0.78' || ($constantVersion[1] ?? '') !== '0.78') {
    $fail('Plugin version declarations must both be 0.78.');
}

foreach (['class-bcs-release-078.php', 'BCS_Release_078::init();'] as $needle) {
    if (!str_contains($bootstrap, $needle)) $fail('Release 0.78 is not loaded: '.$needle);
}

$required = [
    "remove_action('wp_ajax_bcs_046_organizer_otp_send', ['BCS_Release_046'",
    "remove_action('wp_ajax_bcs_046_organizer_otp_verify', ['BCS_Release_051'",
    "add_action('wp_ajax_bcs_046_organizer_otp_send', [__CLASS__, 'ajax_send_organizer_otp'])",
    "add_action('wp_ajax_bcs_046_organizer_otp_verify', [__CLASS__, 'ajax_verify_organizer_otp'])",
    "'sms_message_id'=>\$smsMessageId",
    "'sms_id'=>\$smsMessageId",
    "'accepted_at'=>\$now",
    "'verified_at'=>\$now",
    "'agreement_id'=>\$agreementId",
    "'source'=>'organizer_otp_verify_078'",
    'proof_snapshot',
    'restore_proof',
    'cleanup_stale_proofs',
    "BCS_Release_051::repair_registration(\$registration_id, true)",
    "'workflow'=>'parent_first_078'",
];
foreach ($required as $needle) {
    if (!str_contains($source, $needle)) $fail('Release 0.78 implementation is incomplete: '.$needle);
}

$proofWrite = strpos($source, 'update_option($proofKey, $proof, false)');
$stateWrite = strpos($source, '$updated = $wpdb->update(BCS_DB::table(\'registrations\')');
$finalRepair = strpos($source, 'BCS_Release_051::repair_registration($registration_id, true)');
$transientDelete = strpos($source, 'delete_transient(self::request_key($registration_id));', $finalRepair ?: 0);
if ($proofWrite === false || $stateWrite === false || $finalRepair === false || $transientDelete === false) {
    $fail('Could not locate the organizer signature finalization sequence.');
}
if (!($proofWrite < $stateWrite && $stateWrite < $finalRepair && $finalRepair < $transientDelete)) {
    $fail('Organizer proof/state/final-document sequence is not ordered safely.');
}

$rollbackCount = substr_count($source, 'self::restore_proof($proofKey, $previousProof);');
if ($rollbackCount < 3) {
    $fail('Organizer proof is not rolled back on all relevant failure paths.');
}

if (!str_contains($source, "\$data['sms_message_id'] ?? \$data['sms_id']")) {
    $fail('0.78 must read the canonical SMS message ID with legacy sms_id fallback.');
}
if (!str_contains($source, 'BCS_Utils::now()')) {
    $fail('Organizer acceptance time must be generated by the Basketmania Warsaw-time utility.');
}
if (!str_contains($source, "delete_option(self::proof_key((int)\$row->agreement_id));")) {
    $fail('A new organizer OTP send must invalidate any stale organizer proof.');
}

echo "Release 0.78 organizer proof checks passed.\n";
