<?php
if (!defined('ABSPATH')) exit;
final class BCS_Release_0194 {
 public static function init():void{add_action('wp_ajax_bcs_update_registration_price_0194',[self::class,'price']);add_action('admin_head',[self::class,'css'],900);add_action('admin_footer',[self::class,'js'],900);}
 public static function price():void{if(!current_user_can('manage_options'))wp_send_json_error(['message'=>'Brak uprawnień.'],403);check_ajax_referer('bcs_update_registration_price_0194','nonce');$id=absint($_POST['registration_id']??0);$amount=round((float)str_replace([' ', ','],['','.'],(string)($_POST['amount']??'')),2);if(!$id||$amount<=0)wp_send_json_error(['message'=>'Podaj prawidłową cenę.'],422);global $wpdb;$r=$wpdb->get_row($wpdb->prepare("SELECT r.*,a.status agreement_real_status FROM ".BCS_DB::table('registrations')." r LEFT JOIN ".BCS_DB::table('agreements')." a ON a.id=r.agreement_id WHERE r.id=%d",$id));if(!$r)wp_send_json_error(['message'=>'Nie znaleziono zgłoszenia.'],404);$locked=$r->status==='cancelled'||in_array((string)$r->agreement_status,['pending','accepted'],true)||in_array((string)$r->agreement_real_status,['pending','accepted'],true)||!empty($r->agreement_sent_at);if($locked)wp_send_json_error(['message'=>'Cena jest zablokowana po wysłaniu umowy do podpisu.'],409);$ok=$wpdb->update(BCS_DB::table('registrations'),['total_amount'=>$amount,'updated_at'=>BCS_Utils::now()],['id'=>$id]);if($ok===false)wp_send_json_error(['message'=>'Nie udało się zapisać ceny.'],500);if(!empty($r->agreement_id)&&(string)$r->agreement_real_status==='draft'&&class_exists('BCS_Agreements'))BCS_Agreements::build_for_registration($id,'draft',false);BCS_Utils::log('registration_price_changed',['previous_amount'=>(float)$r->total_amount,'amount'=>$amount,'actor'=>'administrator'],$id,(int)($r->agreement_id??0));wp_send_json_success(['message'=>'Cena została zaktualizowana.','amount'=>number_format($amount,2,',',' ').' zł']);}
 public static function css():void{if(!is_admin())return;?><style>
.bcs-admin-ui-0194 button,.bcs-admin-ui-0194 input[type="button"],.bcs-admin-ui-0194 input[type="submit"],.bcs-admin-ui-0194 input[type="reset"],.bcs-admin-ui-0194 a.button,.bcs-admin-ui-0194 .button,.bcs-admin-ui-0194 [class*="bcs-btn"],.bcs-admin-ui-0194 [class*="bcs-action"]{border-radius:8px!important}\n.bcs-admin-ui-0194 a.button,.bcs-admin-ui-0194 .button,.bcs-admin-ui-0194 [class*="bcs-btn"],.bcs-admin-ui-0194 [class*="bcs-action"]{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box}\n.bcs-crm-layout>aside{display:block!important;visibility:visible!important;opacity:1!important}.bcs-crm-layout>aside>.bcs-quick-actions{display:block!important;visibility:visible!important;opacity:1!important;position:relative!important;top:auto!important;margin:0 0 18px!important}
.bcs-settings-flat-0194{display:block!important;border:1px solid #d8dee8!important;border-radius:14px!important;background:#fff!important;box-shadow:0 6px 20px rgba(15,23,42,.05)!important;margin:0 0 18px!important;overflow:hidden!important}.bcs-settings-flat-0194>summary{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:18px 20px!important;background:#fff!important;cursor:pointer!important;font-size:16px!important;font-weight:800!important;color:#172033!important}.bcs-settings-docs-flat-0194>summary .dashicons,.bcs-settings-docs-flat-0194 h2 .dashicons,.bcs-settings-docs-flat-0194 h3 .dashicons{color:#f97316!important}
.bcs-price-modal-0194[hidden]{display:none!important}.bcs-price-modal-0194{position:fixed;inset:0;z-index:100100;display:grid;place-items:center;padding:20px}.bcs-price-modal-0194__backdrop{position:absolute;inset:0;background:rgba(15,23,42,.58);backdrop-filter:blur(2px)}.bcs-price-modal-0194__dialog{position:relative;z-index:1;width:min(460px,calc(100vw - 32px));background:#fff;border-radius:20px;padding:26px;box-shadow:0 28px 90px rgba(15,23,42,.35);animation:bcsPriceIn0194 .18s ease-out}.bcs-price-modal-0194__icon{display:grid;place-items:center;width:54px;height:54px;border-radius:15px;background:#fff7ed;color:#f97316;font-size:26px;margin-bottom:14px}.bcs-price-modal-0194 h2{margin:0 0 6px;font-size:23px}.bcs-price-modal-0194 p{margin:0 0 18px;color:#64748b}.bcs-price-modal-0194 label{display:grid;gap:8px;font-weight:800}.bcs-price-modal-0194 input{width:100%;font-size:26px;font-weight:900;text-align:center;padding:13px;border:2px solid #fdba74;border-radius:12px;box-sizing:border-box}.bcs-price-modal-0194__actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.bcs-price-modal-0194__error{min-height:20px;margin-top:10px;color:#b91c1c;font-weight:700}@keyframes bcsPriceIn0194{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:none}}
</style><?php }
 public static function js():void{if(!is_admin()||!current_user_can('manage_options'))return;$page=sanitize_key(wp_unslash($_GET['page']??''));$id=absint($_GET['view']??0);?><div class="bcs-price-modal-0194" id="bcs-price-modal-0194" hidden><div class="bcs-price-modal-0194__backdrop" data-price-close></div><div class="bcs-price-modal-0194__dialog" role="dialog" aria-modal="true"><div class="bcs-price-modal-0194__icon">✎</div><h2>Zmień cenę zgłoszenia</h2><p>Nowa kwota zostanie użyta we wzorze umowy. Po wysłaniu umowy do podpisu edycja zostanie zablokowana.</p><label>Nowa cena brutto<input id="bcs-price-input-0194" inputmode="decimal" autocomplete="off"></label><div class="bcs-price-modal-0194__error" id="bcs-price-error-0194"></div><div class="bcs-price-modal-0194__actions"><button type="button" class="button" data-price-close>Anuluj</button><button type="button" class="button button-primary bcs-price-save-0194">Zapisz cenę</button></div></div></div><script>
(function(){const page=<?php echo wp_json_encode($page);?>,id=<?php echo (int)$id;?>,ajax=<?php echo wp_json_encode(admin_url('admin-ajax.php'));?>,nonce=<?php echo wp_json_encode(wp_create_nonce('bcs_update_registration_price_0194'));?>;
if(page&&page.indexOf('bcs-')===0)document.body.classList.add('bcs-admin-ui-0194');\nfunction quick(){if(page!=='bcs-registrations'||!id)return;const layout=document.querySelector('.bcs-crm-layout');if(!layout)return;let aside=layout.querySelector(':scope>aside');if(!aside){aside=document.createElement('aside');layout.appendChild(aside)}const q=document.querySelector('.bcs-quick-actions'),e=document.querySelector('.bcs-email-panel');if(!q)return;q.style.display='block';q.style.visibility='visible';q.style.opacity='1';if(e){if(e.parentElement!==aside)aside.appendChild(e);if(q.parentElement!==aside||q.nextElementSibling!==e)aside.insertBefore(q,e)}else if(q.parentElement!==aside)aside.prepend(q)}
function section(title){const h=[...document.querySelectorAll('summary,h1,h2,h3,strong')].find(x=>(x.textContent||'').trim().toLowerCase()===title.toLowerCase());return h?(h.closest('details,.bcs-settings-section-0187,.bcs-settings-card,section')||h.parentElement):null}
function settings(){if(page!=='bcs-settings')return;const email=section('E-MAIL')||section('E-mail'),notify=section('Ustawienia powiadomień')||section('Powiadomienia workflow'),docs=section('Ustawienia dokumentów i automatyzacji');[notify,docs].forEach(x=>x&&x.classList.add('bcs-settings-flat-0194'));if(docs)docs.classList.add('bcs-settings-docs-flat-0194');if(email&&notify)email.after(notify)}
function price(){if(page!=='bcs-registrations'||!id)return;const old=document.querySelector('.bcs-price-edit-0193,.bcs-price-edit-0190');if(!old||old.dataset.modal0194)return;const b=old.cloneNode(true);old.replaceWith(b);b.dataset.modal0194='1';const m=document.getElementById('bcs-price-modal-0194'),i=document.getElementById('bcs-price-input-0194'),er=document.getElementById('bcs-price-error-0194'),save=m.querySelector('.bcs-price-save-0194');const p=[...document.querySelectorAll('.bcs-stat-grid>div')].find(x=>x.querySelector('span')?.textContent.trim()==='Płatność');const mt=(p?.querySelector('strong')?.textContent||'').match(/\/\s*([\d\s]+[,.]\d{2})\s*zł/),cur=mt?mt[1].replace(/\s/g,''):'0,00';const close=()=>{m.hidden=true;er.textContent='';document.body.style.overflow=''};b.onclick=()=>{i.value=cur;m.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>{i.focus();i.select()},30)};m.querySelectorAll('[data-price-close]').forEach(x=>x.onclick=close);save.onclick=async()=>{er.textContent='';save.disabled=true;try{const r=await fetch(ajax,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({action:'bcs_update_registration_price_0194',nonce,registration_id:String(id),amount:i.value})}),j=await r.json();if(!r.ok||!j.success)throw new Error(j?.data?.message||'Nie udało się zmienić ceny.');close();if(typeof window.bcsPopup0190==='function')window.bcsPopup0190(j.data.message,true);else{const p=document.getElementById('bcs-result-popup-0190');if(p){p.className='bcs-result-popup-0190 success show';p.querySelector('h3').textContent=j.data.message}}setTimeout(()=>location.reload(),1000)}catch(e){er.textContent=e.message}finally{save.disabled=false}}}
quick();settings();price();setTimeout(()=>{quick();settings();price()},150);if(page==='bcs-registrations'&&id)new MutationObserver(quick).observe(document.body,{childList:true,subtree:true});})();</script><?php }
}
