<?php
if (!defined('ABSPATH')) exit;

final class BCS_Release_032_List_Hotfix {
    public static function init(): void {
        remove_action('admin_footer', ['BCS_Release_032', 'admin_footer']);
        add_action('admin_footer', [__CLASS__, 'admin_footer']);
    }

    public static function admin_footer(): void {
        if (!current_user_can('manage_options')) return;
        $nonce = wp_create_nonce('bcs_admin');
        ?>
        <style>
        .bcs-otp032-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.62);display:flex;align-items:center;justify-content:center;z-index:100000;padding:20px}.bcs-otp032-modal{width:min(520px,100%);background:#fff;border-radius:18px;box-shadow:0 24px 70px rgba(15,23,42,.3);overflow:hidden}.bcs-otp032-head{padding:24px 26px;background:linear-gradient(135deg,#111827,#334155);color:#fff;display:flex;gap:16px;align-items:center}.bcs-otp032-modal.is-list .bcs-otp032-head{background:linear-gradient(135deg,#ea580c,#f97316)}.bcs-otp032-icon{width:48px;height:48px;border-radius:14px;background:rgba(255,255,255,.16);display:grid;place-items:center;font-size:25px}.bcs-otp032-head h2{margin:0;color:#fff;font-size:21px}.bcs-otp032-head p{margin:4px 0 0;color:#fff7ed}.bcs-otp032-body{padding:26px}.bcs-otp032-status{padding:13px 15px;border-radius:10px;background:#f1f5f9;margin-bottom:18px}.bcs-otp032-code{display:flex;gap:8px;justify-content:center;margin:22px 0}.bcs-otp032-code input{width:48px;height:58px;text-align:center;font-size:26px;font-weight:700;border:2px solid #cbd5e1;border-radius:10px}.bcs-otp032-code input:focus{border-color:#ea580c;box-shadow:0 0 0 3px rgba(234,88,12,.15);outline:0}.bcs-otp032-actions{display:flex;justify-content:flex-end;gap:10px}.bcs-otp032-error{color:#b91c1c;background:#fef2f2;padding:10px 12px;border-radius:8px;margin-top:12px}.bcs-otp032-success{color:#166534;background:#f0fdf4;padding:10px 12px;border-radius:8px;margin-top:12px}
        </style>
        <script>
        (()=>{
            let bypass=false,busy=false;
            const nonce='<?php echo esc_js($nonce); ?>';
            const actionOf=(button,form)=>{const values=[button?.dataset?.action,button?.dataset?.workflowAction,button?.name==='quick_action'?button.value:'',button?.name==='card_action'?button.value:'',button?.name==='bcs_workflow_action'?button.value:''];['quick_action','card_action','bcs_workflow_action','workflow_action'].forEach(name=>{const input=form?.querySelector('[name="'+name+'"]');if(input)values.push(input.value)});return values.find(value=>value==='send_agreement')||''};
            const registrationId=(button,form)=>{const row=button?.closest('tr[data-id]');const values=[button?.dataset?.registrationId,row?.dataset?.id,form?.querySelector('[name="registration_id"]')?.value,form?.querySelector('[name="id"]')?.value];return parseInt(values.find(value=>/^\d+$/.test(String(value||'')))||'0',10)};
            const post=async data=>{const formData=new FormData();Object.entries(data).forEach(([key,value])=>formData.append(key,value));const response=await fetch(ajaxurl,{method:'POST',credentials:'same-origin',body:formData});return response.json()};
            const openModal=isList=>{document.querySelector('.bcs-otp032-backdrop')?.remove();const backdrop=document.createElement('div');backdrop.className='bcs-otp032-backdrop';backdrop.innerHTML='<div class="bcs-otp032-modal '+(isList?'is-list':'')+'" role="dialog" aria-modal="true"><div class="bcs-otp032-head"><div class="bcs-otp032-icon">✉</div><div><h2>Potwierdzenie Organizatora</h2><p>Autoryzacja wysłania umowy kodem SMS</p></div></div><div class="bcs-otp032-body"><div class="bcs-otp032-status" data-status>Wysyłamy kod na numer zapisany w danych Organizatora…</div><div class="bcs-otp032-code" data-code hidden>'+Array.from({length:6},(_,index)=>'<input inputmode="numeric" maxlength="1" autocomplete="one-time-code" aria-label="Cyfra '+(index+1)+'">').join('')+'</div><div class="bcs-otp032-error" data-error hidden></div><div class="bcs-otp032-success" data-success hidden></div><div class="bcs-otp032-actions"><button type="button" class="button" data-cancel>Anuluj</button><button type="button" class="button button-primary" data-verify disabled>Potwierdź i wyślij umowę</button></div></div></div>';document.body.appendChild(backdrop);return backdrop};
            const begin=async(button,form,replay)=>{if(busy)return;const id=registrationId(button,form);if(!id)return;busy=true;const isList=!!button?.closest('tr[data-id]');const modal=openModal(isList);const status=modal.querySelector('[data-status]'),error=modal.querySelector('[data-error]'),success=modal.querySelector('[data-success]'),codeWrap=modal.querySelector('[data-code]'),verify=modal.querySelector('[data-verify]'),cancel=modal.querySelector('[data-cancel]');const close=()=>{modal.remove();busy=false};cancel.onclick=close;let sent;try{sent=await post({action:'bcs_organizer_agreement_otp_send_030',nonce,registration_id:id})}catch(e){status.textContent='Nie można wysłać kodu.';error.hidden=false;error.textContent='Błąd połączenia z serwerem.';busy=false;return}if(!sent.success){status.textContent='Nie można wysłać kodu.';error.hidden=false;error.textContent=sent.data&&sent.data.message||'Wystąpił błąd.';busy=false;return}status.innerHTML='<strong>'+sent.data.organizer+'</strong><br>Kod wysłano na '+sent.data.phone+'. Wpisz 6 cyfr poniżej.';codeWrap.hidden=false;const inputs=[...codeWrap.querySelectorAll('input')];const update=()=>verify.disabled=inputs.some(input=>!input.value);inputs.forEach((input,index)=>{input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'').slice(-1);if(input.value&&inputs[index+1])inputs[index+1].focus();update()});input.addEventListener('keydown',event=>{if(event.key==='Backspace'&&!input.value&&inputs[index-1])inputs[index-1].focus()});input.addEventListener('paste',event=>{const digits=(event.clipboardData.getData('text')||'').replace(/\D/g,'').slice(0,6);if(!digits)return;event.preventDefault();digits.split('').forEach((digit,i)=>{if(inputs[i])inputs[i].value=digit});inputs[Math.min(digits.length,6)-1].focus();update()})});inputs[0].focus();verify.onclick=async()=>{verify.disabled=true;error.hidden=true;success.hidden=true;const code=inputs.map(input=>input.value).join('');let checked;try{checked=await post({action:'bcs_organizer_agreement_otp_verify_030',nonce,registration_id:id,code})}catch(e){error.hidden=false;error.textContent='Błąd połączenia podczas weryfikacji kodu.';verify.disabled=false;return}if(!checked.success){error.hidden=false;error.textContent=checked.data&&checked.data.message||'Kod jest nieprawidłowy.';verify.disabled=false;inputs.forEach(input=>input.value='');inputs[0].focus();return}success.hidden=false;success.textContent=checked.data.message||'Kod został potwierdzony.';status.innerHTML='<strong>Potwierdzono tożsamość Organizatora.</strong><br>Umowa jest przekazywana do rodzica.';verify.textContent='Wysyłanie…';cancel.disabled=true;setTimeout(()=>{modal.remove();busy=false;bypass=true;replay();setTimeout(()=>bypass=false,1800)},450)}};
            document.addEventListener('click',event=>{if(bypass)return;const button=event.target.closest('button,a,input[type="submit"]');if(!button)return;const form=button.closest('form');if(actionOf(button,form)!=='send_agreement')return;const id=registrationId(button,form);if(!id)return;event.preventDefault();event.stopImmediatePropagation();begin(button,form,()=>{if(form&&button.tagName!=='A'&&form.requestSubmit)form.requestSubmit(button);else button.click()})},true);
            document.addEventListener('submit',event=>{if(bypass)return;const form=event.target;const button=event.submitter||form.querySelector('button[type="submit"],input[type="submit"]');if(actionOf(button,form)!=='send_agreement')return;const id=registrationId(button,form);if(!id)return;event.preventDefault();event.stopImmediatePropagation();begin(button,form,()=>form.requestSubmit?form.requestSubmit(button):form.submit())},true);
        })();
        </script>
        <?php
    }
}
