<?php
if (!defined('ABSPATH')) exit;

class BCS_Documents {
    public static function init(): void {
        add_action('admin_post_nopriv_bcs_download_document', [__CLASS__, 'download_document']);
        add_action('admin_post_bcs_download_document', [__CLASS__, 'download_document']);
        add_action('admin_post_nopriv_bcs_download_package', [__CLASS__, 'download_package']);
        add_action('template_redirect', [__CLASS__, 'public_download']);
        add_action('admin_post_bcs_download_package', [__CLASS__, 'download_package']);
    }
    public static function uploads_dir(): string { $u=wp_upload_dir();$dir=trailingslashit($u['basedir']).'basketmania-documents';if(!is_dir($dir))wp_mkdir_p($dir);return $dir; }
    public static function clean_name(string $name): string { return sanitize_file_name(remove_accents($name)); }
    public static function document_token(int $id, string $document): string {
        $document = sanitize_key($document);
        return hash_hmac('sha256', $id.'|'.$document, wp_salt('auth'));
    }
    public static function download_url(int $id,string $document,string $token=''): string {
        $document=sanitize_key($document);
        $args=['bcs_document'=>1,'registration'=>$id,'document'=>$document,'token'=>self::document_token($id,$document)];
        return add_query_arg($args,home_url('/'));
    }
    public static function public_download(): void { if(empty($_GET['bcs_document'])) return; self::download_document(); exit; }
    private static function row(int $id): ?object { global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT r.*,c.name camp_name,c.start_date,c.end_date,c.location,a.agreement_number,o.name organizer_name,o.address organizer_address,o.nip organizer_nip,a.html agreement_html,a.status agreement_status,a.accepted_at,a.accepted_phone_masked,a.sms_message_id,a.document_hash FROM ".BCS_DB::table('registrations')." r JOIN ".BCS_DB::table('camps')." c ON c.id=r.camp_id LEFT JOIN ".BCS_DB::table('organizers')." o ON o.id=c.organizer_id LEFT JOIN ".BCS_DB::table('agreements')." a ON a.id=r.agreement_id WHERE r.id=%d",$id)); }
    private static function authorized(object $r,string $document,string $token): bool {
        if($token==='') return false;
        return hash_equals(self::document_token((int)$r->id,$document),$token);
    }
    private static function dir(int $id): string { $dir=self::uploads_dir().'/registration-'.$id;if(!is_dir($dir))wp_mkdir_p($dir);return $dir; }
    private static function pdf_or_error(string $html,string $path,string $title): string { if(!BCS_PDF::generate($html,$path,$title))return '';return $path; }
    public static function form_pdf(int $id): string { $r=self::row($id);if(!$r)return '';$body='<h1>Formularz zgłoszeniowy - obozowy</h1><p class="small">Zgłoszenie #'.(int)$r->id.' | wygenerowano '.esc_html(BCS_Utils::today('d.m.Y H:i')).'</p>'.self::data_table($r);return self::pdf_or_error(self::html_document('Formularz zgłoszeniowy', $body),self::dir($id).'/01-formularz-zgloszeniowy.pdf','Formularz zgłoszeniowy'); }
    public static function agreement_pdf(int $id,string $stage='current'): string { global $wpdb;$r=self::row($id);if(!$r||!$r->agreement_number)return '';$html='';$label='Umowa';if(in_array($stage,['draft','sent','signed'],true)){$v=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".BCS_DB::table('agreement_versions')." WHERE registration_id=%d AND stage=%s ORDER BY id DESC LIMIT 1",$id,$stage));if($v){$html=$v->html;$label=['draft'=>'Draft umowy','sent'=>'Umowa wysłana','signed'=>'Umowa podpisana'][$stage];}}if($html==='')$html=(string)$r->agreement_html;if($stage==='signed'&&$r->agreement_status==='accepted'&&!str_contains($html,'Cyfrowe potwierdzenie podpisania umowy')){$vars=['{{AGREEMENT_NUMBER}}'=>$r->agreement_number,'{{ACCEPTED_AT}}'=>$r->accepted_at,'{{PHONE_MASKED}}'=>$r->parent_phone,'{{SMS_ID}}'=>$r->sms_message_id,'{{DOCUMENT_HASH}}'=>$r->document_hash];$html.=BCS_Template_Engine::render(BCS_Template_Engine::get('documents','agreement_proof'),$vars);}$name='02-'.self::clean_name(strtolower(str_replace(' ','-',$label))).'.pdf';return self::pdf_or_error(self::html_document($label.' '.$r->agreement_number,$html),self::dir($id).'/'.$name,$label); }
    public static function regulations_pdf(int $id): string {
        $r=self::row($id); if(!$r) return '';
        $vars=[
            '{{CAMP_NAME}}'=>esc_html((string)$r->camp_name),
            '{{CAMP_DATES}}'=>esc_html(trim((string)$r->start_date.' – '.(string)$r->end_date)),
            '{{CAMP_LOCATION}}'=>esc_html((string)$r->location),
            '{{ORGANIZER_NAME}}'=>esc_html((string)$r->organizer_name),
            '{{ORGANIZER_ADDRESS}}'=>nl2br(esc_html((string)$r->organizer_address)),
            '{{ORGANIZER_NIP}}'=>esc_html((string)$r->organizer_nip),
        ];
        $html=BCS_Template_Engine::render(BCS_Template_Engine::get('documents','regulations'),$vars);
        return self::pdf_or_error(self::html_document('Regulamin obozu', $html),self::dir($id).'/03-regulamin-obozu.pdf','Regulamin obozu');
    }
    public static function invoice_path(int $id): string { global $wpdb;$invoice=$wpdb->get_row($wpdb->prepare("SELECT file_path FROM ".BCS_DB::table('invoices')." WHERE registration_id=%d ORDER BY id DESC LIMIT 1",$id));return ($invoice && !empty($invoice->file_path) && file_exists($invoice->file_path))?(string)$invoice->file_path:''; }
    public static function complete_pdf(int $id): string { global $wpdb;$r=self::row($id);if(!$r)return '';$invoice=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".BCS_DB::table('invoices')." WHERE registration_id=%d ORDER BY id DESC LIMIT 1",$id));$ready=($r->form_status==='complete'&&!empty($r->form_verified_at)&&$r->agreement_status==='accepted'&&(float)$r->total_amount>0&&(float)$r->paid_amount>=(float)$r->total_amount&&$r->invoice_status==='sent'&&$invoice);if(!$ready)return '';$proof=['{{AGREEMENT_NUMBER}}'=>$r->agreement_number,'{{ACCEPTED_AT}}'=>$r->accepted_at,'{{PHONE_MASKED}}'=>$r->parent_phone,'{{SMS_ID}}'=>$r->sms_message_id,'{{DOCUMENT_HASH}}'=>$r->document_hash];$body='<h1>Komplet dokumentów Basketmania Camp</h1><h2>1. Formularz zgłoszeniowy</h2>'.self::data_table($r).'<div class="page-break"></div><h2>2. Podpisana umowa</h2>'.(string)$r->agreement_html.BCS_Template_Engine::render(BCS_Template_Engine::get('documents','agreement_proof'),$proof).'<div class="page-break"></div><h2>3. Płatność i dokument sprzedaży</h2><table><tr><th>Status płatności</th><td>Opłacono w całości</td></tr><tr><th>Kwota</th><td>'.number_format((float)$r->paid_amount,2,',',' ').' zł</td></tr><tr><th>Numer faktury / rachunku</th><td>'.esc_html($invoice->invoice_number).'</td></tr><tr><th>Data wystawienia</th><td>'.esc_html($invoice->issue_date).'</td></tr><tr><th>Kwota brutto</th><td>'.number_format((float)$invoice->gross_amount,2,',',' ').' zł</td></tr></table>';$path=self::dir($id).'/00-komplet-dokumentow.pdf';return self::pdf_or_error(self::html_document('Komplet dokumentów',$body),$path,'Komplet dokumentów'); }
    private static function data_table(object $r): string { $invoice_address=trim((string)($r->invoice_street??'')."\n".trim((string)($r->invoice_postal_code??'').' '.(string)($r->invoice_city??'')));$rows=['Opiekun'=>trim($r->parent_first_name.' '.$r->parent_last_name),'Imiona i nazwiska rodziców'=>$r->parents_names??'','E-mail'=>$r->parent_email,'Telefon I'=>$r->parent_phone,'Telefon II'=>$r->parent_phone_alt??'','Adres opiekuna'=>BCS_Utils::registration_address($r),'Uczestnik'=>trim($r->child_first_name.' '.$r->child_last_name),'Adres uczestnika (jeżeli inny)'=>$r->child_address??'','Data urodzenia'=>$r->child_birth_date,'PESEL'=>$r->child_pesel,'Wzrost'=>$r->child_height?((int)$r->child_height.' cm'):'','Waga'=>!empty($r->child_weight)?rtrim(rtrim(number_format((float)$r->child_weight,1,'.',''),'0'),'.').' kg':'','Rozmiar stroju'=>$r->shirt_size,'Klub'=>$r->child_club,'Specjalne potrzeby edukacyjne'=>$r->special_educational_needs??'','Stan zdrowia, rozwój psychofizyczny i leki'=>$r->medical_notes,'Dieta, alergie i nietolerancje'=>$r->dietary_notes,'Szczepienie przeciw tężcowi – rok'=>$r->vaccination_tetanus??'','Szczepienie przeciw błonicy – rok'=>$r->vaccination_diphtheria??'','Inne szczepienia'=>$r->vaccination_other??'','Kontakt podczas pobytu'=>$r->stay_contact,'Osoby upoważnione do odbioru'=>$r->authorized_pickup,'Dodatkowe informacje dla organizatora'=>$r->camp_notes,'Faktura'=>!empty($r->invoice_requested)?'tak':'nie','Nabywca faktury'=>$r->invoice_buyer_name??'','Adres do faktury'=>$invoice_address,'NIP nabywcy'=>$r->invoice_nip??'','Dodatkowe dane na fakturze'=>$r->invoice_notes??'','Turnus'=>$r->camp_name,'Termin'=>$r->start_date.' - '.$r->end_date,'Miejsce'=>$r->location];$html='<table>';foreach($rows as $k=>$v)$html.='<tr><th>'.esc_html($k).'</th><td>'.nl2br(esc_html(trim((string)$v)!==''?(string)$v:'-')).'</td></tr>';return $html.'</table>'; }
    public static function build_package_attachments(int $id): array { return array_values(array_filter([self::form_pdf($id),self::agreement_pdf($id,'signed'),BCS_Invoices::existing_path($id)],'file_exists')); }
    public static function generate_documents(int $id): array { return self::build_package_attachments($id); }
    public static function html_document(string $title,string $body): string { return '<!doctype html><html lang="pl"><head><meta charset="utf-8"><title>'.esc_html($title).'</title><style>@page{margin:12mm}body{font-family:"DejaVu Sans",sans-serif;line-height:1.35;color:#111827;font-size:10px}h1{color:#e85d04;font-size:22px}h2{color:#c2410c;font-size:16px;margin-top:20px}table{border-collapse:collapse;width:100%;margin:10px 0}td,th{border:1px solid #d6d9df;padding:6px;text-align:left;vertical-align:top}th{background:#fff7ed;color:#7c2d12}.small{font-size:8px;color:#667085}.page-break{page-break-before:always}.proof{border:1px solid #f97316;padding:12px 14px;margin-top:20px}.proof h2{margin:0 0 6px}.proof p{margin:0;line-height:1.25}.invoice-sheet{font-size:9px;color:#111}.invoice-head,.invoice-parties,.invoice-payment,.invoice-signatures{table-layout:fixed}.invoice-head td,.invoice-parties td,.invoice-payment td,.invoice-signatures td{border:0}.invoice-logo{width:52%;vertical-align:middle}.invoice-logo img{width:210px;height:auto}.invoice-meta{width:48%}.invoice-meta div{background:#ececec;border-bottom:2px solid #fff;text-align:center;padding:3px 8px}.invoice-meta span{display:block;font-size:8px}.invoice-meta strong{font-size:10px}.invoice-parties{margin-top:28px}.invoice-parties td{width:50%;padding:0 22px 0 0}.invoice-parties td+td{padding:0 0 0 22px}.invoice-bar{background:#e6e6e6;border-top:1px solid #111;text-align:center;font-weight:bold;padding:3px;margin-bottom:6px}.invoice-title{text-align:center;color:#111;font-size:20px;margin:30px 0 14px}.invoice-items th,.invoice-items td{border:1px solid #222;padding:4px}.invoice-items th{text-align:center;background:#ddd;color:#111;font-size:8px}.invoice-items td{text-align:center}.invoice-items td:nth-child(2){text-align:left}.invoice-total td{font-weight:bold}.invoice-total td:first-child{text-align:right}.invoice-payment{margin-top:28px}.invoice-payment td{width:50%;padding:0 22px 0 0}.invoice-payment td+td{padding:0 0 0 22px}.invoice-payment hr{border:0;border-top:1px solid #111;margin:6px 0}.invoice-note{border-top:1px solid #111;padding-top:7px;margin-top:22px}.invoice-signatures{margin-top:32px}.invoice-signatures td{width:50%;padding:0 22px}.signature-space{height:62px;border:1px solid #111}.invoice-signatures small{display:block;text-align:center;margin-top:3px}</style></head><body>'.$body.'</body></html>'; }
    public static function download_document(): void { $id=absint($_GET['registration']??0);$type=sanitize_key(wp_unslash($_GET['document']??''));$token=sanitize_text_field(wp_unslash($_GET['token']??''));$r=self::row($id);if(!$r||!self::authorized($r,$type,$token)){BCS_Utils::log('document_download_denied',['document'=>$type,'reason'=>$token===''?'missing_token':'invalid_token','ip'=>BCS_Utils::client_ip()],$id,null);wp_die('Nieprawidłowy dostęp.','Basketmania Camp',['response'=>403]);}if($type==='form' && empty($r->form_verified_at) && !current_user_can('manage_options')) wp_die('Formularz PDF będzie dostępny po zaakceptowaniu go przez Organizatora.','Basketmania Camp',['response'=>403]);$path=match($type){'form'=>self::form_pdf($id),'agreement_draft'=>self::agreement_pdf($id,'draft'),'agreement_sent'=>self::agreement_pdf($id,'sent'),'agreement_signed'=>self::agreement_pdf($id,'signed'),'agreement_current'=>self::agreement_pdf($id,'current'),'invoice'=>self::invoice_path($id),'complete'=>self::complete_pdf($id),default=>''};if($type==='invoice' && $path && file_exists($path) && !current_user_can('manage_options')) { global $wpdb; $invoice_id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".BCS_DB::table('invoices')." WHERE registration_id=%d ORDER BY id DESC LIMIT 1",$id)); if($invoice_id) BCS_Invoices::record_parent_download($invoice_id,'parent_portal_document'); }if(!$path||!file_exists($path))wp_die(BCS_PDF::available()?'Dokument nie jest jeszcze dostępny.':'Dompdf nie jest zainstalowany. Zainstaluj zależności Composer w katalogu wtyczki.');BCS_Utils::log('document_downloaded',['document'=>$type,'file'=>basename($path),'ip'=>BCS_Utils::client_ip()],$id,(int)$r->agreement_id);self::stream($path); }
    private static function stream(string $path): void { nocache_headers();header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.basename($path).'"');header('Content-Length: '.filesize($path));readfile($path);exit; }
    public static function package_path(int $id): string { return self::complete_pdf($id); }
    public static function download_package(): void { $_GET['document']='complete';self::download_document(); }
}
